ci: publishing (tag+npm)
zazuko/cube-link pull request #116
Opened 2023-11-06 11:29 UTC by tpluscode

2023-11-06 11:37 UTC, ludovicm67 requested changes
There is no `release` script as I can see in the `package.json`.

Also, is tagging not good enough?
If we really want to publish on NPM, can we scope it to the `@zazuko` namespace?

2023-11-06 12:00 UTC, tpluscode commented
> Also, is tagging not good enough?

I think changesets does not tag if there is no publishing script. Might try setting it to private to prevent NPM. Not sure about `@zazuko` org

2023-11-06 12:12 UTC, giacomociti approved these changes

2023-11-06 13:41 UTC, ludovicm67 commented
> I think changesets does not tag if there is no publishing script.

But if it tries to call it using `yarn release`, then it will throw an error, no?

> Might try setting it to private to prevent NPM.

Yes, good idea!
And also add the release script to `changeset tag` like I did here for example: https://github.com/zazuko/fuseki-geosparql/blob/main/package.json#L11

> Not sure about `@zazuko` org

This is only if you want to release it as a NPM module, so you can ignore this since the idea is not to publish it to NPM ;)

2023-11-06 13:42 UTC, ludovicm67 commented on package.json
> +    "release": "changeset publish"
```suggestion
    "release": "changeset tag"
```

2023-11-06 13:42 UTC, ludovicm67 commented on .github/workflows/release.yaml
> +      - name: Create Release Pull Request or Publish to npm
```suggestion
      - name: Create Release Pull Request or Create a GitHub Realease + tag
```

2023-11-07 10:35 UTC, tpluscode commented
Ok @ludovicm67, let's skip NPM for now

2023-11-07 10:43 UTC, ludovicm67 commented
Looks good!

Do you think having the `"private": true,` in the `package.json` is something that we can have?
And if so, then just update the changeset `config.json` configuration, to add the following:

```json
  "privatePackages": {
    "tag": true,
    "version": true
  },
```

like I did here: https://github.com/zazuko/fuseki-geosparql/blob/96fecb758225d1ff5232ca14fe4becf189b1ec7b/.changeset/config.json#L10C1-L13C5

2023-11-07 12:20 UTC, merged