deduplicate minCount|maxCount Violations
zazuko/cube-link pull request #186
Opened 2024-04-22 07:16 UTC by Rdataflow

The current implementation catches Violations twice (once only will do 😄 )

```Violation: "sh:maxCount needs to be 1" at focus node _:b89_b89_b90_anon2dgenid2d6499f875b0c2499c8204f64b9ba131932d3 with path <http://www.w3.org/ns/shacl#maxCount> (HasValueConstraintComponent of source: _:b89_b781)
Violation: "sh:maxCount needs to be 1" at focus node _:b89_b89_b90_anon2dgenid2d6499f875b0c2499c8204f64b9ba131932d3 with path <http://www.w3.org/ns/shacl#maxCount> (MinCountConstraintComponent of source: _:b89_b781)
```

2024-04-22 07:23 UTC, giacomociti requested changes
`sh:hasValue` makes `sh:minCount 1` redundant but we can leave `sh:maxCount 1` to prevent multiple values

2024-04-22 15:46 UTC, Rdataflow commented
@giacomociti thank you for catching this :+1:

2024-04-24 08:53 UTC, tpluscode approved these changes

2024-04-24 13:15 UTC, giacomociti approved these changes

2024-04-24 13:15 UTC, merged